/*
 Highcharts JS v8.1.2 (2020-08-10)

 (c) 2016-2019 Highsoft AS
 Authors: Jon Arild Nygard

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/sunburst",["highcharts"],function(w){b(w);b.Highcharts=w;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function w(b,e,t,M){b.hasOwnProperty(e)||(b[e]=M.apply(null,t))}b=b?b._modules:{};w(b,"mixins/draw-point.js",[],function(){var b=function(b){return"function"===typeof b},e=function(e){var t,p=this,g=p.graphic,n=e.animatableAttribs,
D=e.onComplete,h=e.css,l=e.renderer,E=null===(t=p.series)||void 0===t?void 0:t.options.animation;if(p.shouldDraw())g||(p.graphic=g=l[e.shapeType](e.shapeArgs).add(e.group)),g.css(h).attr(e.attribs).animate(n,e.isNew?!1:E,D);else if(g){var I=function(){p.graphic=g=g.destroy();b(D)&&D()};Object.keys(n).length?g.animate(n,void 0,function(){I()}):I()}};return{draw:e,drawPoint:function(b){(b.attribs=b.attribs||{})["class"]=this.getClassName();e.call(this,b)},isFn:b}});w(b,"mixins/tree-series.js",[b["Core/Color.js"],
b["Core/Utilities.js"]],function(b,e){var t=e.extend,L=e.isArray,p=e.isNumber,g=e.isObject,n=e.merge,D=e.pick;return{getColor:function(h,l){var e=l.index,n=l.mapOptionsToLevel,g=l.parentColor,t=l.parentColorIndex,B=l.series,G=l.colors,p=l.siblings,y=B.points,C=B.chart.options.chart,H;if(h){y=y[h.i];h=n[h.level]||{};if(n=y&&h.colorByPoint){var A=y.index%(G?G.length:C.colorCount);var L=G&&G[A]}if(!B.chart.styledMode){G=y&&y.options.color;C=h&&h.color;if(H=g)H=(H=h&&h.colorVariation)&&"brightness"===
H.key?b.parse(g).brighten(e/p*H.to).get():g;H=D(G,C,L,H,B.color)}var w=D(y&&y.options.colorIndex,h&&h.colorIndex,A,t,l.colorIndex)}return{color:H,colorIndex:w}},getLevelOptions:function(b){var l=null;if(g(b)){l={};var e=p(b.from)?b.from:1;var h=b.levels;var F={};var D=g(b.defaults)?b.defaults:{};L(h)&&(F=h.reduce(function(b,l){if(g(l)&&p(l.level)){var h=n({},l);var E="boolean"===typeof h.levelIsConstant?h.levelIsConstant:D.levelIsConstant;delete h.levelIsConstant;delete h.level;l=l.level+(E?0:e-1);
g(b[l])?t(b[l],h):b[l]=h}return b},{}));h=p(b.to)?b.to:1;for(b=0;b<=h;b++)l[b]=n({},D,g(F[b])?F[b]:{})}return l},setTreeValues:function I(b,e){var l=e.before,n=e.idRoot,g=e.mapIdToNode[n],p=e.points[b.i],E=p&&p.options||{},y=0,C=[];t(b,{levelDynamic:b.level-(("boolean"===typeof e.levelIsConstant?e.levelIsConstant:1)?0:g.level),name:D(p&&p.name,""),visible:n===b.id||("boolean"===typeof e.visible?e.visible:!1)});"function"===typeof l&&(b=l(b,e));b.children.forEach(function(l,n){var g=t({},e);t(g,{index:n,
siblings:b.children.length,visible:b.visible});l=I(l,g);C.push(l);l.visible&&(y+=l.val)});b.visible=0<y||b.visible;l=D(E.value,y);t(b,{children:C,childrenTotal:y,isLeaf:b.visible&&!y,val:l});return b},updateRootId:function(b){if(g(b)){var e=g(b.options)?b.options:{};e=D(b.rootNode,e.rootId,"");g(b.userOptions)&&(b.userOptions.rootId=e);b.rootNode=e}return e}}});w(b,"Series/TreemapSeries.js",[b["Core/Globals.js"],b["mixins/tree-series.js"],b["mixins/draw-point.js"],b["Core/Color.js"],b["mixins/legend-symbol.js"],
b["Core/Series/Point.js"],b["Core/Utilities.js"]],function(b,e,t,w,p,g,n){var D=w.parse,h=n.addEvent,l=n.correctFloat,E=n.defined,I=n.error,F=n.extend,L=n.fireEvent,B=n.isArray,G=n.isNumber,M=n.isObject,y=n.isString,C=n.merge,H=n.objectEach,A=n.pick;w=n.seriesType;var Q=n.stableSort,N=b.seriesTypes;n=b.noop;var O=e.getColor,P=e.getLevelOptions,J=b.Series,R=function(a,c,d){d=d||this;H(a,function(q,k){c.call(d,q,k,a)})},f=function(a,c,d){d=d||this;a=c.call(d,a);!1!==a&&f(a,c,d)},m=e.updateRootId,x=
!1;w("treemap","scatter",{allowTraversingTree:!1,animationLimit:250,showInLegend:!1,marker:!1,colorByPoint:!1,dataLabels:{defer:!1,enabled:!0,formatter:function(){var a=this&&this.point?this.point:{};return y(a.name)?a.name:""},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:"",pointFormat:"<b>{point.name}</b>: {point.value}<br/>"},ignoreHiddenPoint:!0,layoutAlgorithm:"sliceAndDice",layoutStartingDirection:"vertical",alternateStartingDirection:!1,levelIsConstant:!0,drillUpButton:{position:{align:"right",
x:-10,y:10}},traverseUpButton:{position:{align:"right",x:-10,y:10}},borderColor:"#e6e6e6",borderWidth:1,colorKey:"colorValue",opacity:.15,states:{hover:{borderColor:"#999999",brightness:N.heatmap?0:.1,halo:!1,opacity:.75,shadow:!1}}},{pointArrayMap:["value"],directTouch:!0,optionalAxis:"colorAxis",getSymbol:n,parallelArrays:["x","y","value","colorValue"],colorKey:"colorValue",trackerGroups:["group","dataLabelsGroup"],getListOfParents:function(a,c){a=B(a)?a:[];var d=B(c)?c:[];c=a.reduce(function(a,
c,d){c=A(c.parent,"");"undefined"===typeof a[c]&&(a[c]=[]);a[c].push(d);return a},{"":[]});R(c,function(a,c,f){""!==c&&-1===d.indexOf(c)&&(a.forEach(function(a){f[""].push(a)}),delete f[c])});return c},getTree:function(){var a=this.data.map(function(a){return a.id});a=this.getListOfParents(this.data,a);this.nodeMap=[];return this.buildNode("",-1,0,a,null)},hasData:function(){return!!this.processedXData.length},init:function(a,c){var d=b.colorMapSeriesMixin;d&&(this.colorAttribs=d.colorAttribs);this.eventsToUnbind.push(h(this,
"setOptions",function(a){a=a.userOptions;E(a.allowDrillToNode)&&!E(a.allowTraversingTree)&&(a.allowTraversingTree=a.allowDrillToNode,delete a.allowDrillToNode);E(a.drillUpButton)&&!E(a.traverseUpButton)&&(a.traverseUpButton=a.drillUpButton,delete a.drillUpButton)}));J.prototype.init.call(this,a,c);delete this.opacity;this.options.allowTraversingTree&&this.eventsToUnbind.push(h(this,"click",this.onClickDrillToNode))},buildNode:function(a,c,d,f,k){var b=this,q=[],u=b.points[c],e=0,r;(f[a]||[]).forEach(function(c){r=
b.buildNode(b.points[c].id,c,d+1,f,a);e=Math.max(r.height+1,e);q.push(r)});c={id:a,i:c,children:q,height:e,level:d,parent:k,visible:!1};b.nodeMap[c.id]=c;u&&(u.node=c);return c},setTreeValues:function(a){var c=this,d=c.options,f=c.nodeMap[c.rootNode];d="boolean"===typeof d.levelIsConstant?d.levelIsConstant:!0;var k=0,b=[],v=c.points[a.i];a.children.forEach(function(a){a=c.setTreeValues(a);b.push(a);a.ignore||(k+=a.val)});Q(b,function(a,c){return a.sortIndex-c.sortIndex});var u=A(v&&v.options.value,
k);v&&(v.value=u);F(a,{children:b,childrenTotal:k,ignore:!(A(v&&v.visible,!0)&&0<u),isLeaf:a.visible&&!k,levelDynamic:a.level-(d?0:f.level),name:A(v&&v.name,""),sortIndex:A(v&&v.sortIndex,-u),val:u});return a},calculateChildrenAreas:function(a,c){var d=this,f=d.options,k=d.mapOptionsToLevel[a.level+1],b=A(d[k&&k.layoutAlgorithm]&&k.layoutAlgorithm,f.layoutAlgorithm),v=f.alternateStartingDirection,u=[];a=a.children.filter(function(a){return!a.ignore});k&&k.layoutStartingDirection&&(c.direction="vertical"===
k.layoutStartingDirection?0:1);u=d[b](c,a);a.forEach(function(a,f){f=u[f];a.values=C(f,{val:a.childrenTotal,direction:v?1-c.direction:c.direction});a.pointValues=C(f,{x:f.x/d.axisRatio,y:100-f.y-f.height,width:f.width/d.axisRatio});a.children.length&&d.calculateChildrenAreas(a,a.values)})},setPointValues:function(){var a=this,c=a.xAxis,d=a.yAxis,f=a.chart.styledMode;a.points.forEach(function(k){var b=k.node,q=b.pointValues;b=b.visible;if(q&&b){b=q.height;var u=q.width,e=q.x,m=q.y,x=f?0:(a.pointAttribs(k)["stroke-width"]||
0)%2/2;q=Math.round(c.toPixels(e,!0))-x;u=Math.round(c.toPixels(e+u,!0))-x;e=Math.round(d.toPixels(m,!0))-x;b=Math.round(d.toPixels(m+b,!0))-x;k.shapeArgs={x:Math.min(q,u),y:Math.min(e,b),width:Math.abs(u-q),height:Math.abs(b-e)};k.plotX=k.shapeArgs.x+k.shapeArgs.width/2;k.plotY=k.shapeArgs.y+k.shapeArgs.height/2}else delete k.plotX,delete k.plotY})},setColorRecursive:function(a,c,d,f,b){var k=this,q=k&&k.chart;q=q&&q.options&&q.options.colors;if(a){var e=O(a,{colors:q,index:f,mapOptionsToLevel:k.mapOptionsToLevel,
parentColor:c,parentColorIndex:d,series:k,siblings:b});if(c=k.points[a.i])c.color=e.color,c.colorIndex=e.colorIndex;(a.children||[]).forEach(function(c,d){k.setColorRecursive(c,e.color,e.colorIndex,d,a.children.length)})}},algorithmGroup:function(a,c,d,f){this.height=a;this.width=c;this.plot=f;this.startDirection=this.direction=d;this.lH=this.nH=this.lW=this.nW=this.total=0;this.elArr=[];this.lP={total:0,lH:0,nH:0,lW:0,nW:0,nR:0,lR:0,aspectRatio:function(a,c){return Math.max(a/c,c/a)}};this.addElement=
function(a){this.lP.total=this.elArr[this.elArr.length-1];this.total+=a;0===this.direction?(this.lW=this.nW,this.lP.lH=this.lP.total/this.lW,this.lP.lR=this.lP.aspectRatio(this.lW,this.lP.lH),this.nW=this.total/this.height,this.lP.nH=this.lP.total/this.nW,this.lP.nR=this.lP.aspectRatio(this.nW,this.lP.nH)):(this.lH=this.nH,this.lP.lW=this.lP.total/this.lH,this.lP.lR=this.lP.aspectRatio(this.lP.lW,this.lH),this.nH=this.total/this.width,this.lP.nW=this.lP.total/this.nH,this.lP.nR=this.lP.aspectRatio(this.lP.nW,
this.nH));this.elArr.push(a)};this.reset=function(){this.lW=this.nW=0;this.elArr=[];this.total=0}},algorithmCalcPoints:function(a,c,d,f){var b,q,e,m,x=d.lW,r=d.lH,h=d.plot,n=0,g=d.elArr.length-1;if(c)x=d.nW,r=d.nH;else var p=d.elArr[d.elArr.length-1];d.elArr.forEach(function(a){if(c||n<g)0===d.direction?(b=h.x,q=h.y,e=x,m=a/e):(b=h.x,q=h.y,m=r,e=a/m),f.push({x:b,y:q,width:e,height:l(m)}),0===d.direction?h.y+=m:h.x+=e;n+=1});d.reset();0===d.direction?d.width-=x:d.height-=r;h.y=h.parent.y+(h.parent.height-
d.height);h.x=h.parent.x+(h.parent.width-d.width);a&&(d.direction=1-d.direction);c||d.addElement(p)},algorithmLowAspectRatio:function(a,c,d){var f=[],b=this,e,m={x:c.x,y:c.y,parent:c},x=0,h=d.length-1,r=new this.algorithmGroup(c.height,c.width,c.direction,m);d.forEach(function(d){e=d.val/c.val*c.height*c.width;r.addElement(e);r.lP.nR>r.lP.lR&&b.algorithmCalcPoints(a,!1,r,f,m);x===h&&b.algorithmCalcPoints(a,!0,r,f,m);x+=1});return f},algorithmFill:function(a,c,d){var f=[],b,e=c.direction,m=c.x,x=c.y,
h=c.width,r=c.height,l,n,g,p;d.forEach(function(d){b=d.val/c.val*c.height*c.width;l=m;n=x;0===e?(p=r,g=b/p,h-=g,m+=g):(g=h,p=b/g,r-=p,x+=p);f.push({x:l,y:n,width:g,height:p});a&&(e=1-e)});return f},strip:function(a,c){return this.algorithmLowAspectRatio(!1,a,c)},squarified:function(a,c){return this.algorithmLowAspectRatio(!0,a,c)},sliceAndDice:function(a,c){return this.algorithmFill(!0,a,c)},stripes:function(a,c){return this.algorithmFill(!1,a,c)},translate:function(){var a=this,c=a.options,d=m(a);
J.prototype.translate.call(a);var b=a.tree=a.getTree();var k=a.nodeMap[d];a.renderTraverseUpButton(d);a.mapOptionsToLevel=P({from:k.level+1,levels:c.levels,to:b.height,defaults:{levelIsConstant:a.options.levelIsConstant,colorByPoint:c.colorByPoint}});""===d||k&&k.children.length||(a.setRootNode("",!1),d=a.rootNode,k=a.nodeMap[d]);f(a.nodeMap[a.rootNode],function(c){var d=!1,b=c.parent;c.visible=!0;if(b||""===b)d=a.nodeMap[b];return d});f(a.nodeMap[a.rootNode].children,function(a){var c=!1;a.forEach(function(a){a.visible=
!0;a.children.length&&(c=(c||[]).concat(a.children))});return c});a.setTreeValues(b);a.axisRatio=a.xAxis.len/a.yAxis.len;a.nodeMap[""].pointValues=d={x:0,y:0,width:100,height:100};a.nodeMap[""].values=d=C(d,{width:d.width*a.axisRatio,direction:"vertical"===c.layoutStartingDirection?0:1,val:b.val});a.calculateChildrenAreas(b,d);a.colorAxis||c.colorByPoint||a.setColorRecursive(a.tree);c.allowTraversingTree&&(c=k.pointValues,a.xAxis.setExtremes(c.x,c.x+c.width,!1),a.yAxis.setExtremes(c.y,c.y+c.height,
!1),a.xAxis.setScale(),a.yAxis.setScale());a.setPointValues()},drawDataLabels:function(){var a=this,c=a.mapOptionsToLevel,d,b;a.points.filter(function(a){return a.node.visible}).forEach(function(f){b=c[f.node.level];d={style:{}};f.node.isLeaf||(d.enabled=!1);b&&b.dataLabels&&(d=C(d,b.dataLabels),a._hasPointLabels=!0);f.shapeArgs&&(d.style.width=f.shapeArgs.width,f.dataLabel&&f.dataLabel.css({width:f.shapeArgs.width+"px"}));f.dlOptions=C(d,f.options.dataLabels)});J.prototype.drawDataLabels.call(this)},
alignDataLabel:function(a,c,d){var b=d.style;!E(b.textOverflow)&&c.text&&c.getBBox().width>c.text.textWidth&&c.css({textOverflow:"ellipsis",width:b.width+="px"});N.column.prototype.alignDataLabel.apply(this,arguments);a.dataLabel&&a.dataLabel.attr({zIndex:(a.node.zIndex||0)+1})},pointAttribs:function(a,c){var d=M(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},b=a&&d[a.node.level]||{};d=this.options;var f=c&&d.states[c]||{},e=a&&a.getClassName()||"";a={stroke:a&&a.borderColor||b.borderColor||f.borderColor||
d.borderColor,"stroke-width":A(a&&a.borderWidth,b.borderWidth,f.borderWidth,d.borderWidth),dashstyle:a&&a.borderDashStyle||b.borderDashStyle||f.borderDashStyle||d.borderDashStyle,fill:a&&a.color||this.color};-1!==e.indexOf("highcharts-above-level")?(a.fill="none",a["stroke-width"]=0):-1!==e.indexOf("highcharts-internal-node-interactive")?(c=A(f.opacity,d.opacity),a.fill=D(a.fill).setOpacity(c).get(),a.cursor="pointer"):-1!==e.indexOf("highcharts-internal-node")?a.fill="none":c&&(a.fill=D(a.fill).brighten(f.brightness).get());
return a},drawPoints:function(){var a=this,c=a.chart,d=c.renderer,b=c.styledMode,f=a.options,e=b?{}:f.shadow,m=f.borderRadius,x=c.pointCount<f.animationLimit,h=f.allowTraversingTree;a.points.forEach(function(c){var q=c.node.levelDynamic,k={},l={},n={},g="level-group-"+q,u=!!c.graphic,S=x&&u,K=c.shapeArgs;c.shouldDraw()&&(m&&(l.r=m),C(!0,S?k:l,u?K:{},b?{}:a.pointAttribs(c,c.selected&&"select")),a.colorAttribs&&b&&F(n,a.colorAttribs(c)),a[g]||(a[g]=d.g(g).attr({zIndex:1E3-q}).add(a.group),a[g].survive=
!0));c.draw({animatableAttribs:k,attribs:l,css:n,group:a[g],renderer:d,shadow:e,shapeArgs:K,shapeType:"rect"});h&&c.graphic&&(c.drillId=f.interactByLeaf?a.drillToByLeaf(c):a.drillToByGroup(c))})},onClickDrillToNode:function(a){var c=(a=a.point)&&a.drillId;y(c)&&(this.isDrillAllowed?this.isDrillAllowed(c):1)&&(a.setState(""),this.setRootNode(c,!0,{trigger:"click"}))},drillToByGroup:function(a){var c=!1;1!==a.node.level-this.nodeMap[this.rootNode].level||a.node.isLeaf||(c=a.id);return c},drillToByLeaf:function(a){var c=
!1;if(a.node.parent!==this.rootNode&&a.node.isLeaf)for(a=a.node;!c;)a=this.nodeMap[a.parent],a.parent===this.rootNode&&(c=a.id);return c},drillUp:function(){var a=this.nodeMap[this.rootNode];a&&y(a.parent)&&this.setRootNode(a.parent,!0,{trigger:"traverseUpButton"})},drillToNode:function(a,c){I(32,!1,void 0,{"treemap.drillToNode":"use treemap.setRootNode"});this.setRootNode(a,c)},setRootNode:function(a,c,d){a=F({newRootId:a,previousRootId:this.rootNode,redraw:A(c,!0),series:this},d);L(this,"setRootNode",
a,function(a){var c=a.series;c.idPreviousRoot=a.previousRootId;c.rootNode=a.newRootId;c.isDirty=!0;a.redraw&&c.chart.redraw()})},isDrillAllowed:function(a){var c=this.tree,d=c.children[0];return!(1===c.children.length&&(""===this.rootNode&&a===d.id||this.rootNode===d.id&&""===a))},renderTraverseUpButton:function(a){var c=this,d=c.nodeMap[a],b=c.options.traverseUpButton,f=A(b.text,d.name,"< Back");""!==a&&(!c.isDrillAllowed||y(d.parent)&&c.isDrillAllowed(d.parent))?this.drillUpButton?(this.drillUpButton.placed=
!1,this.drillUpButton.attr({text:f}).align()):(d=(a=b.theme)&&a.states,this.drillUpButton=this.chart.renderer.button(f,null,null,function(){c.drillUp()},a,d&&d.hover,d&&d.select).addClass("highcharts-drillup-button").attr({align:b.position.align,zIndex:7}).add().align(b.position,!1,b.relativeTo||"plotBox")):c.drillUpButton&&(c.drillUpButton=c.drillUpButton.destroy())},buildKDTree:n,drawLegendSymbol:p.drawRectangle,getExtremes:function(){var a=J.prototype.getExtremes.call(this,this.colorValueData),
c=a.dataMax;this.valueMin=a.dataMin;this.valueMax=c;return J.prototype.getExtremes.call(this)},getExtremesFromAll:!0,setState:function(a){this.options.inactiveOtherPoints=!0;J.prototype.setState.call(this,a,!1);this.options.inactiveOtherPoints=!1},utils:{recursive:f}},{draw:t.drawPoint,setVisible:N.pie.prototype.pointClass.prototype.setVisible,getClassName:function(){var a=g.prototype.getClassName.call(this),c=this.series,d=c.options;this.node.level<=c.nodeMap[c.rootNode].level?a+=" highcharts-above-level":
this.node.isLeaf||A(d.interactByLeaf,!d.allowTraversingTree)?this.node.isLeaf||(a+=" highcharts-internal-node"):a+=" highcharts-internal-node-interactive";return a},isValid:function(){return this.id||G(this.value)},setState:function(a){g.prototype.setState.call(this,a);this.graphic&&this.graphic.attr({zIndex:"hover"===a?1:0})},shouldDraw:function(){return G(this.plotY)&&null!==this.y}});h(b.Series,"afterBindAxes",function(){var a=this.xAxis,c=this.yAxis;if(a&&c)if(this.is("treemap")){var d={endOnTick:!1,
gridLineWidth:0,lineWidth:0,min:0,dataMin:0,minPadding:0,max:100,dataMax:100,maxPadding:0,startOnTick:!1,title:null,tickPositions:[]};F(c.options,d);F(a.options,d);x=!0}else x&&(c.setOptions(c.userOptions),a.setOptions(a.userOptions),x=!1)});""});w(b,"Series/SunburstSeries.js",[b["Core/Globals.js"],b["Core/Utilities.js"],b["mixins/centered-series.js"],b["mixins/draw-point.js"],b["mixins/tree-series.js"]],function(b,e,t,w,p){var g=e.correctFloat,n=e.error,D=e.extend,h=e.isNumber,l=e.isObject,E=e.isString,
I=e.merge,F=e.seriesType,L=e.splat,B=b.Series,G=t.getCenter,M=p.getColor,y=p.getLevelOptions,C=t.getStartAndEndRadians,H=180/Math.PI,A=b.seriesTypes,Q=p.setTreeValues,N=p.updateRootId,O=function(b,e){var f=[];if(h(b)&&h(e)&&b<=e)for(;b<=e;b++)f.push(b);return f},P=function(b,e){e=l(e)?e:{};var f=0,a;if(l(b)){var c=I({},b);b=h(e.from)?e.from:0;var d=h(e.to)?e.to:0;var q=O(b,d);b=Object.keys(c).filter(function(a){return-1===q.indexOf(+a)});var k=a=h(e.diffRadius)?e.diffRadius:0;q.forEach(function(b){b=
c[b];var d=b.levelSize.unit,e=b.levelSize.value;"weight"===d?f+=e:"percentage"===d?(b.levelSize={unit:"pixels",value:e/100*k},a-=b.levelSize.value):"pixels"===d&&(a-=e)});q.forEach(function(b){var d=c[b];"weight"===d.levelSize.unit&&(d=d.levelSize.value,c[b].levelSize={unit:"pixels",value:d/f*a})});b.forEach(function(a){c[a].levelSize={value:0,unit:"pixels"}})}return c},J=function(b){var f=b.level;return{from:0<f?f:1,to:f+b.height}},R=function(b,e){var f=e.mapIdToNode[b.parent],a=e.series,c=a.chart,
d=a.points[b.i];f=M(b,{colors:a.options.colors||c&&c.options.colors,colorIndex:a.colorIndex,index:e.index,mapOptionsToLevel:e.mapOptionsToLevel,parentColor:f&&f.color,parentColorIndex:f&&f.colorIndex,series:e.series,siblings:e.siblings});b.color=f.color;b.colorIndex=f.colorIndex;d&&(d.color=b.color,d.colorIndex=b.colorIndex,b.sliced=b.id!==e.idRoot?d.sliced:!1);return b};F("sunburst","treemap",{center:["50%","50%"],colorByPoint:!1,opacity:1,dataLabels:{allowOverlap:!0,defer:!0,rotationMode:"auto",
style:{textOverflow:"ellipsis"}},rootId:void 0,levelIsConstant:!0,levelSize:{value:1,unit:"weight"},slicedOffset:10},{drawDataLabels:b.noop,drawPoints:function(){var b=this,e=b.mapOptionsToLevel,x=b.shapeRoot,a=b.group,c=b.hasRendered,d=b.rootNode,q=b.idPreviousRoot,k=b.nodeMap,g=k[q],n=g&&g.shapeArgs;g=b.points;var u=b.startAndEndRadians,p=b.chart,r=p&&p.options&&p.options.chart||{},y="boolean"===typeof r.animation?r.animation:!0,t=b.center[3]/2,A=b.chart.renderer,w=!1,C=!1;if(r=!!(y&&c&&d!==q&&
b.dataLabelsGroup)){b.dataLabelsGroup.attr({opacity:0});var E=function(){w=!0;b.dataLabelsGroup&&b.dataLabelsGroup.animate({opacity:1,visibility:"visible"})}}g.forEach(function(f){var g=f.node,m=e[g.level];var r=f.shapeExisting||{};var v=g.shapeArgs||{},w=!(!g.visible||!g.shapeArgs);if(c&&y){var K={};var F={end:v.end,start:v.start,innerR:v.innerR,r:v.r,x:v.x,y:v.y};w?!f.graphic&&n&&(K=d===f.id?{start:u.start,end:u.end}:n.end<=v.start?{start:u.end,end:u.end}:{start:u.start,end:u.start},K.innerR=K.r=
t):f.graphic&&(q===f.id?F={innerR:t,r:t}:x&&(F=x.end<=r.start?{innerR:t,r:t,start:u.end,end:u.end}:{innerR:t,r:t,start:u.start,end:u.start}));r=K}else F=v,r={};K=[v.plotX,v.plotY];if(!f.node.isLeaf)if(d===f.id){var z=k[d];z=z.parent}else z=f.id;D(f,{shapeExisting:v,tooltipPos:K,drillId:z,name:""+(f.name||f.id||f.index),plotX:v.plotX,plotY:v.plotY,value:g.val,isNull:!w});z=f.options;g=l(v)?v:{};z=l(z)?z.dataLabels:{};m=L(l(m)?m.dataLabels:{})[0];m=I({style:{}},m,z);z=m.rotationMode;if(!h(m.rotation)){if("auto"===
z||"circular"===z)if(1>f.innerArcLength&&f.outerArcLength>g.radius){var B=0;f.dataLabelPath&&"circular"===z&&(m.textPath={enabled:!0})}else 1<f.innerArcLength&&f.outerArcLength>1.5*g.radius?"circular"===z?m.textPath={enabled:!0,attributes:{dy:5}}:z="parallel":(f.dataLabel&&f.dataLabel.textPathWrapper&&"circular"===z&&(m.textPath={enabled:!1}),z="perpendicular");"auto"!==z&&"circular"!==z&&(B=g.end-(g.end-g.start)/2);m.style.width="parallel"===z?Math.min(2.5*g.radius,(f.outerArcLength+f.innerArcLength)/
2):g.radius;"perpendicular"===z&&f.series.chart.renderer.fontMetrics(m.style.fontSize).h>f.outerArcLength&&(m.style.width=1);m.style.width=Math.max(m.style.width-2*(m.padding||0),1);B=B*H%180;"parallel"===z&&(B-=90);90<B?B-=180:-90>B&&(B+=180);m.rotation=B}m.textPath&&(0===f.shapeExisting.innerR&&m.textPath.enabled?(m.rotation=0,m.textPath.enabled=!1,m.style.width=Math.max(2*f.shapeExisting.r-2*(m.padding||0),1)):f.dlOptions&&f.dlOptions.textPath&&!f.dlOptions.textPath.enabled&&"circular"===z&&(m.textPath.enabled=
!0),m.textPath.enabled&&(m.rotation=0,m.style.width=Math.max((f.outerArcLength+f.innerArcLength)/2-2*(m.padding||0),1)));0===m.rotation&&(m.rotation=.001);f.dlOptions=m;if(!C&&w){C=!0;var G=E}f.draw({animatableAttribs:F,attribs:D(r,!p.styledMode&&b.pointAttribs(f,f.selected&&"select")),onComplete:G,group:a,renderer:A,shapeType:"arc",shapeArgs:v})});r&&C?(b.hasRendered=!1,b.options.dataLabels.defer=!0,B.prototype.drawDataLabels.call(b),b.hasRendered=!0,w&&E()):B.prototype.drawDataLabels.call(b)},pointAttribs:A.column.prototype.pointAttribs,
layoutAlgorithm:function(b,e,g){var a=b.start,c=b.end-a,d=b.val,f=b.x,m=b.y,n=g&&l(g.levelSize)&&h(g.levelSize.value)?g.levelSize.value:0,x=b.r,p=x+n,t=g&&h(g.slicedOffset)?g.slicedOffset:0;return(e||[]).reduce(function(b,e){var g=1/d*e.val*c,k=a+g/2,q=f+Math.cos(k)*t;k=m+Math.sin(k)*t;e={x:e.sliced?q:f,y:e.sliced?k:m,innerR:x,r:p,radius:n,start:a,end:a+g};b.push(e);a=e.end;return b},[])},setShapeArgs:function(b,e,g){var a=[],c=g[b.level+1];b=b.children.filter(function(a){return a.visible});a=this.layoutAlgorithm(e,
b,c);b.forEach(function(b,c){c=a[c];var d=c.start+(c.end-c.start)/2,f=c.innerR+(c.r-c.innerR)/2,e=c.end-c.start;f=0===c.innerR&&6.28<e?{x:c.x,y:c.y}:{x:c.x+Math.cos(d)*f,y:c.y+Math.sin(d)*f};var m=b.val?b.childrenTotal>b.val?b.childrenTotal:b.val:b.childrenTotal;this.points[b.i]&&(this.points[b.i].innerArcLength=e*c.innerR,this.points[b.i].outerArcLength=e*c.r);b.shapeArgs=I(c,{plotX:f.x,plotY:f.y+4*Math.abs(Math.cos(d))});b.values=I(c,{val:m});b.children.length&&this.setShapeArgs(b,b.values,g)},
this)},translate:function(){var b=this,e=b.options,g=b.center=G.call(b),a=b.startAndEndRadians=C(e.startAngle,e.endAngle),c=g[3]/2,d=g[2]/2-c,h=N(b),k=b.nodeMap,l=k&&k[h],p={};b.shapeRoot=l&&l.shapeArgs;B.prototype.translate.call(b);var u=b.tree=b.getTree();b.renderTraverseUpButton(h);k=b.nodeMap;l=k[h];var t=E(l.parent)?l.parent:"";t=k[t];var r=J(l);var w=r.from,A=r.to;r=y({from:w,levels:b.options.levels,to:A,defaults:{colorByPoint:e.colorByPoint,dataLabels:e.dataLabels,levelIsConstant:e.levelIsConstant,
levelSize:e.levelSize,slicedOffset:e.slicedOffset}});r=P(r,{diffRadius:d,from:w,to:A});Q(u,{before:R,idRoot:h,levelIsConstant:e.levelIsConstant,mapOptionsToLevel:r,mapIdToNode:k,points:b.points,series:b});e=k[""].shapeArgs={end:a.end,r:c,start:a.start,val:l.val,x:g[0],y:g[1]};this.setShapeArgs(t,e,r);b.mapOptionsToLevel=r;b.data.forEach(function(a){p[a.id]&&n(31,!1,b.chart);p[a.id]=!0});p={}},alignDataLabel:function(b,e,g){if(!g.textPath||!g.textPath.enabled)return A.treemap.prototype.alignDataLabel.apply(this,
arguments)},animate:function(b){var e=this.chart,f=[e.plotWidth/2,e.plotHeight/2],a=e.plotLeft,c=e.plotTop;e=this.group;b?(b={translateX:f[0]+a,translateY:f[1]+c,scaleX:.001,scaleY:.001,rotation:10,opacity:.01},e.attr(b)):(b={translateX:a,translateY:c,scaleX:1,scaleY:1,rotation:0,opacity:1},e.animate(b,this.options.animation))},utils:{calculateLevelSizes:P,getLevelFromAndTo:J,range:O}},{draw:w.drawPoint,shouldDraw:function(){return!this.isNull},isValid:function(){return!0},getDataLabelPath:function(b){var e=
this.series.chart.renderer,f=this.shapeExisting,a=f.start,c=f.end,d=a+(c-a)/2;d=0>d&&d>-Math.PI||d>Math.PI;var h=f.r+(b.options.distance||0);a===-Math.PI/2&&g(c)===g(1.5*Math.PI)&&(a=-Math.PI+Math.PI/360,c=-Math.PI/360,d=!0);if(c-a>Math.PI){d=!1;var k=!0}this.dataLabelPath&&(this.dataLabelPath=this.dataLabelPath.destroy());this.dataLabelPath=e.arc({open:!0,longArc:k?1:0}).add(b);this.dataLabelPath.attr({start:d?a:c,end:d?c:a,clockwise:+d,x:f.x,y:f.y,r:(h+f.innerR)/2});return this.dataLabelPath}})});
w(b,"masters/modules/sunburst.src.js",[],function(){})});
//# sourceMappingURL=sunburst.js.map