/*
 Highcharts JS v8.1.2 (2020-08-10)

 (c) 2014-2019 Highsoft AS
 Authors: Jon Arild Nygard / Oystein Moseng

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/treemap",["highcharts"],function(x){c(x);c.Highcharts=x;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function x(c,d,m,y){c.hasOwnProperty(d)||(c[d]=y.apply(null,m))}c=c?c._modules:{};x(c,"mixins/tree-series.js",[c["Core/Color.js"],c["Core/Utilities.js"]],function(c,d){var m=d.extend,y=d.isArray,n=d.isNumber,l=d.isObject,
h=d.merge,u=d.pick;return{getColor:function(f,g){var t=g.index,m=g.mapOptionsToLevel,h=g.parentColor,l=g.parentColorIndex,d=g.series,D=g.colors,H=g.siblings,p=d.points,z=d.chart.options.chart,A;if(f){p=p[f.i];f=m[f.level]||{};if(m=p&&f.colorByPoint){var w=p.index%(D?D.length:z.colorCount);var y=D&&D[w]}if(!d.chart.styledMode){D=p&&p.options.color;z=f&&f.color;if(A=h)A=(A=f&&f.colorVariation)&&"brightness"===A.key?c.parse(h).brighten(t/H*A.to).get():h;A=u(D,z,y,A,d.color)}var n=u(p&&p.options.colorIndex,
f&&f.colorIndex,w,l,g.colorIndex)}return{color:A,colorIndex:n}},getLevelOptions:function(f){var g=null;if(l(f)){g={};var c=n(f.from)?f.from:1;var d=f.levels;var C={};var u=l(f.defaults)?f.defaults:{};y(d)&&(C=d.reduce(function(g,f){if(l(f)&&n(f.level)){var d=h({},f);var t="boolean"===typeof d.levelIsConstant?d.levelIsConstant:u.levelIsConstant;delete d.levelIsConstant;delete d.level;f=f.level+(t?0:c-1);l(g[f])?m(g[f],d):g[f]=d}return g},{}));d=n(f.to)?f.to:1;for(f=0;f<=d;f++)g[f]=h({},u,l(C[f])?C[f]:
{})}return g},setTreeValues:function L(g,d){var c=d.before,h=d.idRoot,l=d.mapIdToNode[h],t=d.points[g.i],y=t&&t.options||{},p=0,n=[];m(g,{levelDynamic:g.level-(("boolean"===typeof d.levelIsConstant?d.levelIsConstant:1)?0:l.level),name:u(t&&t.name,""),visible:h===g.id||("boolean"===typeof d.visible?d.visible:!1)});"function"===typeof c&&(g=c(g,d));g.children.forEach(function(c,h){var l=m({},d);m(l,{index:h,siblings:g.children.length,visible:g.visible});c=L(c,l);n.push(c);c.visible&&(p+=c.val)});g.visible=
0<p||g.visible;c=u(y.value,p);m(g,{children:n,childrenTotal:p,isLeaf:g.visible&&!p,val:c});return g},updateRootId:function(d){if(l(d)){var c=l(d.options)?d.options:{};c=u(d.rootNode,c.rootId,"");l(d.userOptions)&&(d.userOptions.rootId=c);d.rootNode=c}return c}}});x(c,"mixins/draw-point.js",[],function(){var c=function(d){return"function"===typeof d},d=function(d){var m,n=this,l=n.graphic,h=d.animatableAttribs,u=d.onComplete,f=d.css,g=d.renderer,t=null===(m=n.series)||void 0===m?void 0:m.options.animation;
if(n.shouldDraw())l||(n.graphic=l=g[d.shapeType](d.shapeArgs).add(d.group)),l.css(f).attr(d.attribs).animate(h,d.isNew?!1:t,u);else if(l){var x=function(){n.graphic=l=l.destroy();c(u)&&u()};Object.keys(h).length?l.animate(h,void 0,function(){x()}):x()}};return{draw:d,drawPoint:function(c){(c.attribs=c.attribs||{})["class"]=this.getClassName();d.call(this,c)},isFn:c}});x(c,"Series/TreemapSeries.js",[c["Core/Globals.js"],c["mixins/tree-series.js"],c["mixins/draw-point.js"],c["Core/Color.js"],c["mixins/legend-symbol.js"],
c["Core/Series/Point.js"],c["Core/Utilities.js"]],function(c,d,m,y,n,l,h){var u=y.parse,f=h.addEvent,g=h.correctFloat,t=h.defined,x=h.error,C=h.extend,M=h.fireEvent,K=h.isArray,D=h.isNumber,H=h.isObject,p=h.isString,z=h.merge,A=h.objectEach,w=h.pick;y=h.seriesType;var N=h.stableSort,I=c.seriesTypes;h=c.noop;var O=d.getColor,P=d.getLevelOptions,E=c.Series,Q=function(a,b,e){e=e||this;A(a,function(q,k){b.call(e,q,k,a)})},G=function(a,b,e){e=e||this;a=b.call(e,a);!1!==a&&G(a,b,e)},R=d.updateRootId,J=
!1;y("treemap","scatter",{allowTraversingTree:!1,animationLimit:250,showInLegend:!1,marker:!1,colorByPoint:!1,dataLabels:{defer:!1,enabled:!0,formatter:function(){var a=this&&this.point?this.point:{};return p(a.name)?a.name:""},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:"",pointFormat:"<b>{point.name}</b>: {point.value}<br/>"},ignoreHiddenPoint:!0,layoutAlgorithm:"sliceAndDice",layoutStartingDirection:"vertical",alternateStartingDirection:!1,levelIsConstant:!0,drillUpButton:{position:{align:"right",
x:-10,y:10}},traverseUpButton:{position:{align:"right",x:-10,y:10}},borderColor:"#e6e6e6",borderWidth:1,colorKey:"colorValue",opacity:.15,states:{hover:{borderColor:"#999999",brightness:I.heatmap?0:.1,halo:!1,opacity:.75,shadow:!1}}},{pointArrayMap:["value"],directTouch:!0,optionalAxis:"colorAxis",getSymbol:h,parallelArrays:["x","y","value","colorValue"],colorKey:"colorValue",trackerGroups:["group","dataLabelsGroup"],getListOfParents:function(a,b){a=K(a)?a:[];var e=K(b)?b:[];b=a.reduce(function(a,
b,e){b=w(b.parent,"");"undefined"===typeof a[b]&&(a[b]=[]);a[b].push(e);return a},{"":[]});Q(b,function(a,b,d){""!==b&&-1===e.indexOf(b)&&(a.forEach(function(a){d[""].push(a)}),delete d[b])});return b},getTree:function(){var a=this.data.map(function(a){return a.id});a=this.getListOfParents(this.data,a);this.nodeMap=[];return this.buildNode("",-1,0,a,null)},hasData:function(){return!!this.processedXData.length},init:function(a,b){var e=c.colorMapSeriesMixin;e&&(this.colorAttribs=e.colorAttribs);this.eventsToUnbind.push(f(this,
"setOptions",function(a){a=a.userOptions;t(a.allowDrillToNode)&&!t(a.allowTraversingTree)&&(a.allowTraversingTree=a.allowDrillToNode,delete a.allowDrillToNode);t(a.drillUpButton)&&!t(a.traverseUpButton)&&(a.traverseUpButton=a.drillUpButton,delete a.drillUpButton)}));E.prototype.init.call(this,a,b);delete this.opacity;this.options.allowTraversingTree&&this.eventsToUnbind.push(f(this,"click",this.onClickDrillToNode))},buildNode:function(a,b,e,d,k){var c=this,q=[],F=c.points[b],f=0,v;(d[a]||[]).forEach(function(b){v=
c.buildNode(c.points[b].id,b,e+1,d,a);f=Math.max(v.height+1,f);q.push(v)});b={id:a,i:b,children:q,height:f,level:e,parent:k,visible:!1};c.nodeMap[b.id]=b;F&&(F.node=b);return b},setTreeValues:function(a){var b=this,e=b.options,d=b.nodeMap[b.rootNode];e="boolean"===typeof e.levelIsConstant?e.levelIsConstant:!0;var k=0,c=[],B=b.points[a.i];a.children.forEach(function(a){a=b.setTreeValues(a);c.push(a);a.ignore||(k+=a.val)});N(c,function(a,b){return a.sortIndex-b.sortIndex});var f=w(B&&B.options.value,
k);B&&(B.value=f);C(a,{children:c,childrenTotal:k,ignore:!(w(B&&B.visible,!0)&&0<f),isLeaf:a.visible&&!k,levelDynamic:a.level-(e?0:d.level),name:w(B&&B.name,""),sortIndex:w(B&&B.sortIndex,-f),val:f});return a},calculateChildrenAreas:function(a,b){var e=this,d=e.options,k=e.mapOptionsToLevel[a.level+1],c=w(e[k&&k.layoutAlgorithm]&&k.layoutAlgorithm,d.layoutAlgorithm),f=d.alternateStartingDirection,F=[];a=a.children.filter(function(a){return!a.ignore});k&&k.layoutStartingDirection&&(b.direction="vertical"===
k.layoutStartingDirection?0:1);F=e[c](b,a);a.forEach(function(a,k){k=F[k];a.values=z(k,{val:a.childrenTotal,direction:f?1-b.direction:b.direction});a.pointValues=z(k,{x:k.x/e.axisRatio,y:100-k.y-k.height,width:k.width/e.axisRatio});a.children.length&&e.calculateChildrenAreas(a,a.values)})},setPointValues:function(){var a=this,b=a.xAxis,e=a.yAxis,d=a.chart.styledMode;a.points.forEach(function(k){var c=k.node,f=c.pointValues;c=c.visible;if(f&&c){c=f.height;var q=f.width,g=f.x,h=f.y,r=d?0:(a.pointAttribs(k)["stroke-width"]||
0)%2/2;f=Math.round(b.toPixels(g,!0))-r;q=Math.round(b.toPixels(g+q,!0))-r;g=Math.round(e.toPixels(h,!0))-r;c=Math.round(e.toPixels(h+c,!0))-r;k.shapeArgs={x:Math.min(f,q),y:Math.min(g,c),width:Math.abs(q-f),height:Math.abs(c-g)};k.plotX=k.shapeArgs.x+k.shapeArgs.width/2;k.plotY=k.shapeArgs.y+k.shapeArgs.height/2}else delete k.plotX,delete k.plotY})},setColorRecursive:function(a,b,e,c,k){var d=this,f=d&&d.chart;f=f&&f.options&&f.options.colors;if(a){var q=O(a,{colors:f,index:c,mapOptionsToLevel:d.mapOptionsToLevel,
parentColor:b,parentColorIndex:e,series:d,siblings:k});if(b=d.points[a.i])b.color=q.color,b.colorIndex=q.colorIndex;(a.children||[]).forEach(function(b,e){d.setColorRecursive(b,q.color,q.colorIndex,e,a.children.length)})}},algorithmGroup:function(a,b,e,c){this.height=a;this.width=b;this.plot=c;this.startDirection=this.direction=e;this.lH=this.nH=this.lW=this.nW=this.total=0;this.elArr=[];this.lP={total:0,lH:0,nH:0,lW:0,nW:0,nR:0,lR:0,aspectRatio:function(a,b){return Math.max(a/b,b/a)}};this.addElement=
function(a){this.lP.total=this.elArr[this.elArr.length-1];this.total+=a;0===this.direction?(this.lW=this.nW,this.lP.lH=this.lP.total/this.lW,this.lP.lR=this.lP.aspectRatio(this.lW,this.lP.lH),this.nW=this.total/this.height,this.lP.nH=this.lP.total/this.nW,this.lP.nR=this.lP.aspectRatio(this.nW,this.lP.nH)):(this.lH=this.nH,this.lP.lW=this.lP.total/this.lH,this.lP.lR=this.lP.aspectRatio(this.lP.lW,this.lH),this.nH=this.total/this.width,this.lP.nW=this.lP.total/this.nH,this.lP.nR=this.lP.aspectRatio(this.lP.nW,
this.nH));this.elArr.push(a)};this.reset=function(){this.lW=this.nW=0;this.elArr=[];this.total=0}},algorithmCalcPoints:function(a,b,e,c){var k,d,f,q,h=e.lW,v=e.lH,r=e.plot,l=0,p=e.elArr.length-1;if(b)h=e.nW,v=e.nH;else var m=e.elArr[e.elArr.length-1];e.elArr.forEach(function(a){if(b||l<p)0===e.direction?(k=r.x,d=r.y,f=h,q=a/f):(k=r.x,d=r.y,q=v,f=a/q),c.push({x:k,y:d,width:f,height:g(q)}),0===e.direction?r.y+=q:r.x+=f;l+=1});e.reset();0===e.direction?e.width-=h:e.height-=v;r.y=r.parent.y+(r.parent.height-
e.height);r.x=r.parent.x+(r.parent.width-e.width);a&&(e.direction=1-e.direction);b||e.addElement(m)},algorithmLowAspectRatio:function(a,b,e){var c=[],d=this,f,g={x:b.x,y:b.y,parent:b},h=0,l=e.length-1,v=new this.algorithmGroup(b.height,b.width,b.direction,g);e.forEach(function(e){f=e.val/b.val*b.height*b.width;v.addElement(f);v.lP.nR>v.lP.lR&&d.algorithmCalcPoints(a,!1,v,c,g);h===l&&d.algorithmCalcPoints(a,!0,v,c,g);h+=1});return c},algorithmFill:function(a,b,e){var c=[],d,f=b.direction,g=b.x,h=b.y,
l=b.width,v=b.height,r,p,m,n;e.forEach(function(e){d=e.val/b.val*b.height*b.width;r=g;p=h;0===f?(n=v,m=d/n,l-=m,g+=m):(m=l,n=d/m,v-=n,h+=n);c.push({x:r,y:p,width:m,height:n});a&&(f=1-f)});return c},strip:function(a,b){return this.algorithmLowAspectRatio(!1,a,b)},squarified:function(a,b){return this.algorithmLowAspectRatio(!0,a,b)},sliceAndDice:function(a,b){return this.algorithmFill(!0,a,b)},stripes:function(a,b){return this.algorithmFill(!1,a,b)},translate:function(){var a=this,b=a.options,e=R(a);
E.prototype.translate.call(a);var c=a.tree=a.getTree();var d=a.nodeMap[e];a.renderTraverseUpButton(e);a.mapOptionsToLevel=P({from:d.level+1,levels:b.levels,to:c.height,defaults:{levelIsConstant:a.options.levelIsConstant,colorByPoint:b.colorByPoint}});""===e||d&&d.children.length||(a.setRootNode("",!1),e=a.rootNode,d=a.nodeMap[e]);G(a.nodeMap[a.rootNode],function(b){var e=!1,d=b.parent;b.visible=!0;if(d||""===d)e=a.nodeMap[d];return e});G(a.nodeMap[a.rootNode].children,function(a){var b=!1;a.forEach(function(a){a.visible=
!0;a.children.length&&(b=(b||[]).concat(a.children))});return b});a.setTreeValues(c);a.axisRatio=a.xAxis.len/a.yAxis.len;a.nodeMap[""].pointValues=e={x:0,y:0,width:100,height:100};a.nodeMap[""].values=e=z(e,{width:e.width*a.axisRatio,direction:"vertical"===b.layoutStartingDirection?0:1,val:c.val});a.calculateChildrenAreas(c,e);a.colorAxis||b.colorByPoint||a.setColorRecursive(a.tree);b.allowTraversingTree&&(b=d.pointValues,a.xAxis.setExtremes(b.x,b.x+b.width,!1),a.yAxis.setExtremes(b.y,b.y+b.height,
!1),a.xAxis.setScale(),a.yAxis.setScale());a.setPointValues()},drawDataLabels:function(){var a=this,b=a.mapOptionsToLevel,e,d;a.points.filter(function(a){return a.node.visible}).forEach(function(c){d=b[c.node.level];e={style:{}};c.node.isLeaf||(e.enabled=!1);d&&d.dataLabels&&(e=z(e,d.dataLabels),a._hasPointLabels=!0);c.shapeArgs&&(e.style.width=c.shapeArgs.width,c.dataLabel&&c.dataLabel.css({width:c.shapeArgs.width+"px"}));c.dlOptions=z(e,c.options.dataLabels)});E.prototype.drawDataLabels.call(this)},
alignDataLabel:function(a,b,e){var c=e.style;!t(c.textOverflow)&&b.text&&b.getBBox().width>b.text.textWidth&&b.css({textOverflow:"ellipsis",width:c.width+="px"});I.column.prototype.alignDataLabel.apply(this,arguments);a.dataLabel&&a.dataLabel.attr({zIndex:(a.node.zIndex||0)+1})},pointAttribs:function(a,b){var e=H(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},c=a&&e[a.node.level]||{};e=this.options;var d=b&&e.states[b]||{},f=a&&a.getClassName()||"";a={stroke:a&&a.borderColor||c.borderColor||d.borderColor||
e.borderColor,"stroke-width":w(a&&a.borderWidth,c.borderWidth,d.borderWidth,e.borderWidth),dashstyle:a&&a.borderDashStyle||c.borderDashStyle||d.borderDashStyle||e.borderDashStyle,fill:a&&a.color||this.color};-1!==f.indexOf("highcharts-above-level")?(a.fill="none",a["stroke-width"]=0):-1!==f.indexOf("highcharts-internal-node-interactive")?(b=w(d.opacity,e.opacity),a.fill=u(a.fill).setOpacity(b).get(),a.cursor="pointer"):-1!==f.indexOf("highcharts-internal-node")?a.fill="none":b&&(a.fill=u(a.fill).brighten(d.brightness).get());
return a},drawPoints:function(){var a=this,b=a.chart,e=b.renderer,c=b.styledMode,d=a.options,f=c?{}:d.shadow,g=d.borderRadius,h=b.pointCount<d.animationLimit,l=d.allowTraversingTree;a.points.forEach(function(b){var k=b.node.levelDynamic,q={},m={},p={},n="level-group-"+k,t=!!b.graphic,v=h&&t,u=b.shapeArgs;b.shouldDraw()&&(g&&(m.r=g),z(!0,v?q:m,t?u:{},c?{}:a.pointAttribs(b,b.selected&&"select")),a.colorAttribs&&c&&C(p,a.colorAttribs(b)),a[n]||(a[n]=e.g(n).attr({zIndex:1E3-k}).add(a.group),a[n].survive=
!0));b.draw({animatableAttribs:q,attribs:m,css:p,group:a[n],renderer:e,shadow:f,shapeArgs:u,shapeType:"rect"});l&&b.graphic&&(b.drillId=d.interactByLeaf?a.drillToByLeaf(b):a.drillToByGroup(b))})},onClickDrillToNode:function(a){var b=(a=a.point)&&a.drillId;p(b)&&(this.isDrillAllowed?this.isDrillAllowed(b):1)&&(a.setState(""),this.setRootNode(b,!0,{trigger:"click"}))},drillToByGroup:function(a){var b=!1;1!==a.node.level-this.nodeMap[this.rootNode].level||a.node.isLeaf||(b=a.id);return b},drillToByLeaf:function(a){var b=
!1;if(a.node.parent!==this.rootNode&&a.node.isLeaf)for(a=a.node;!b;)a=this.nodeMap[a.parent],a.parent===this.rootNode&&(b=a.id);return b},drillUp:function(){var a=this.nodeMap[this.rootNode];a&&p(a.parent)&&this.setRootNode(a.parent,!0,{trigger:"traverseUpButton"})},drillToNode:function(a,b){x(32,!1,void 0,{"treemap.drillToNode":"use treemap.setRootNode"});this.setRootNode(a,b)},setRootNode:function(a,b,e){a=C({newRootId:a,previousRootId:this.rootNode,redraw:w(b,!0),series:this},e);M(this,"setRootNode",
a,function(a){var b=a.series;b.idPreviousRoot=a.previousRootId;b.rootNode=a.newRootId;b.isDirty=!0;a.redraw&&b.chart.redraw()})},isDrillAllowed:function(a){var b=this.tree,e=b.children[0];return!(1===b.children.length&&(""===this.rootNode&&a===e.id||this.rootNode===e.id&&""===a))},renderTraverseUpButton:function(a){var b=this,e=b.nodeMap[a],c=b.options.traverseUpButton,d=w(c.text,e.name,"< Back");""!==a&&(!b.isDrillAllowed||p(e.parent)&&b.isDrillAllowed(e.parent))?this.drillUpButton?(this.drillUpButton.placed=
!1,this.drillUpButton.attr({text:d}).align()):(e=(a=c.theme)&&a.states,this.drillUpButton=this.chart.renderer.button(d,null,null,function(){b.drillUp()},a,e&&e.hover,e&&e.select).addClass("highcharts-drillup-button").attr({align:c.position.align,zIndex:7}).add().align(c.position,!1,c.relativeTo||"plotBox")):b.drillUpButton&&(b.drillUpButton=b.drillUpButton.destroy())},buildKDTree:h,drawLegendSymbol:n.drawRectangle,getExtremes:function(){var a=E.prototype.getExtremes.call(this,this.colorValueData),
b=a.dataMax;this.valueMin=a.dataMin;this.valueMax=b;return E.prototype.getExtremes.call(this)},getExtremesFromAll:!0,setState:function(a){this.options.inactiveOtherPoints=!0;E.prototype.setState.call(this,a,!1);this.options.inactiveOtherPoints=!1},utils:{recursive:G}},{draw:m.drawPoint,setVisible:I.pie.prototype.pointClass.prototype.setVisible,getClassName:function(){var a=l.prototype.getClassName.call(this),b=this.series,c=b.options;this.node.level<=b.nodeMap[b.rootNode].level?a+=" highcharts-above-level":
this.node.isLeaf||w(c.interactByLeaf,!c.allowTraversingTree)?this.node.isLeaf||(a+=" highcharts-internal-node"):a+=" highcharts-internal-node-interactive";return a},isValid:function(){return this.id||D(this.value)},setState:function(a){l.prototype.setState.call(this,a);this.graphic&&this.graphic.attr({zIndex:"hover"===a?1:0})},shouldDraw:function(){return D(this.plotY)&&null!==this.y}});f(c.Series,"afterBindAxes",function(){var a=this.xAxis,b=this.yAxis;if(a&&b)if(this.is("treemap")){var c={endOnTick:!1,
gridLineWidth:0,lineWidth:0,min:0,dataMin:0,minPadding:0,max:100,dataMax:100,maxPadding:0,startOnTick:!1,title:null,tickPositions:[]};C(b.options,c);C(a.options,c);J=!0}else J&&(b.setOptions(b.userOptions),a.setOptions(a.userOptions),J=!1)});""});x(c,"masters/modules/treemap.src.js",[],function(){})});
//# sourceMappingURL=treemap.js.map